feat: workflow failing added

diff --git a/.github/workflows/does_run.yml b/.github/workflows/does_run.yml
--- a/.github/workflows/does_run.yml
+++ b/.github/workflows/does_run.yml
@@ -4,6 +4,8 @@ on:
   pull_request:
 
 jobs:
+  # this job will fail if the code doesnot start
+  # preventing some silly errors
   check_linting:
     runs-on: ubuntu-latest
 
@@ -18,13 +20,13 @@ jobs:
 
     - name: Install dependencies
       run: |
-        python -m pip install flake8 black
         python -m pip install --upgrade pip
         python -m pip install -r requirements.txt
 
+    - name: Add dummy .env file
+      run: |
+        cp env.example .env
 
-    - name: Run flake8 linting
-      run: flake8 .
-
-    - name: Run black
-      run: black . --check
+    - name: Run check in django
+      run : |
+        python manage.py check || exit 1
